#include <string.h>
#include "web_server.h"
#include "esp_http_server.h"
#include "cJSON.h"
#include "embedded_ui.h"
#include "state_manager.h"
#include "app_config.h"
#include "wifi_manager.h"
#include "ssr_output.h"
#include "esp_timer.h"
static esp_err_t root(httpd_req_t *r){httpd_resp_send(r,THERMOWORK_UI_HTML,HTTPD_RESP_USE_STRLEN);return ESP_OK;}
static esp_err_t status(httpd_req_t *r){thermowork_inputs_t in; thermowork_config_t c; thermowork_status_t s; thermowork_cloud_status_t cl; state_manager_get_inputs(&in);state_manager_get_config(&c);state_manager_get_status(&s);state_manager_get_cloud(&cl); cJSON *j=cJSON_CreateObject(); cJSON_AddStringToObject(j,"device",THERMOWORK_DEVICE_NAME); cJSON_AddStringToObject(j,"version",THERMOWORK_FW_VERSION); cJSON_AddBoolToObject(j,"wifi_connected",wifi_manager_is_connected()); cJSON_AddStringToObject(j,"wifi_mode",wifi_manager_get_mode()); cJSON_AddStringToObject(j,"ip",wifi_manager_get_ip()); cJSON_AddBoolToObject(j,"enabled",c.enabled); cJSON_AddNumberToObject(j,"grid_power_w",in.grid_power_w); cJSON_AddNumberToObject(j,"temperature_c",in.temperature_c); cJSON_AddNumberToObject(j,"heater_setpoint_w",s.heater_setpoint_w); cJSON_AddNumberToObject(j,"ssr_duty_percent",s.ssr_duty_percent); cJSON_AddBoolToObject(j,"ssr_gpio_state",s.ssr_gpio_state); cJSON_AddNumberToObject(j,"fault_code",s.fault_code); char *t=cJSON_PrintUnformatted(j); httpd_resp_set_type(r,"application/json"); httpd_resp_sendstr(r,t); cJSON_free(t); cJSON_Delete(j); return ESP_OK;}
static esp_err_t post_input(httpd_req_t *r){char b[256]; int n=httpd_req_recv(r,b,sizeof(b)-1); if(n>0){b[n]=0; cJSON *j=cJSON_Parse(b); thermowork_inputs_t in; state_manager_get_inputs(&in); in.grid_power_w=cJSON_GetObjectItem(j,"grid_power_w")?cJSON_GetObjectItem(j,"grid_power_w")->valueint:in.grid_power_w; in.pv_power_w=cJSON_GetObjectItem(j,"pv_power_w")?cJSON_GetObjectItem(j,"pv_power_w")->valueint:in.pv_power_w; in.house_power_w=cJSON_GetObjectItem(j,"house_power_w")?cJSON_GetObjectItem(j,"house_power_w")->valueint:in.house_power_w; in.temperature_c=cJSON_GetObjectItem(j,"temperature_c")?(float)cJSON_GetObjectItem(j,"temperature_c")->valuedouble:in.temperature_c; in.input_valid=true; in.last_update_ms=esp_timer_get_time()/1000; state_manager_set_inputs(&in); cJSON_Delete(j);} httpd_resp_sendstr(r,"{\"ok\":true}"); return ESP_OK;}
static esp_err_t post_test(httpd_req_t *r){char b[128]; int n=httpd_req_recv(r,b,sizeof(b)-1); if(n>0){b[n]=0; cJSON *j=cJSON_Parse(b); cJSON *d=cJSON_GetObjectItem(j,"duty"); if(cJSON_IsNumber(d)) ssr_output_set_duty((uint8_t)d->valueint); cJSON_Delete(j);} httpd_resp_sendstr(r,"{\"ok\":true}"); return ESP_OK;}
static esp_err_t post_gpio(httpd_req_t *r){char b[128]; int n=httpd_req_recv(r,b,sizeof(b)-1); if(n>0){b[n]=0; cJSON *j=cJSON_Parse(b); cJSON *a=cJSON_GetObjectItem(j,"action"); if(cJSON_IsString(a)&&strcmp(a->valuestring,"blink")==0){ssr_output_blink(5,200);} else {cJSON *l=cJSON_GetObjectItem(j,"level"); ssr_output_set_raw_level(cJSON_IsNumber(l)&&l->valueint);} cJSON_Delete(j);} httpd_resp_sendstr(r,"{\"ok\":true}"); return ESP_OK;}
void web_server_start(void){httpd_handle_t s=NULL; httpd_config_t c=HTTPD_DEFAULT_CONFIG(); httpd_start(&s,&c); httpd_uri_t u1={.uri="/",.method=HTTP_GET,.handler=root}; httpd_uri_t u2={.uri="/api/status",.method=HTTP_GET,.handler=status}; httpd_uri_t u3={.uri="/api/input",.method=HTTP_POST,.handler=post_input}; httpd_uri_t u4={.uri="/api/test",.method=HTTP_POST,.handler=post_test}; httpd_uri_t u5={.uri="/api/gpio_test",.method=HTTP_POST,.handler=post_gpio}; httpd_register_uri_handler(s,&u1); httpd_register_uri_handler(s,&u2); httpd_register_uri_handler(s,&u3); httpd_register_uri_handler(s,&u4); httpd_register_uri_handler(s,&u5); }
